DROP DOMAIN IF EXISTS domain_subindustry_name CASCADE;
CREATE DOMAIN domain_subindustry_name TEXT CONSTRAINT constraint_subindustry_name_predefined NOT NULL CHECK (
    VALUE IN (
        'Oil & Gas Drilling',
        'Oil & Gas Equipment & Services',
        'Integrated Oil & Gas',
        'Oil & Gas Exploration & Production',
        'Oil & Gas Refining & Marketing',
        'Oil & Gas Storage & Transportation',
        'Coal & Consumable Fuels',
        'Commodity Chemicals',
        'Diversified Chemicals',
        'Fertilizers & Agricultural Chemicals',
        'Industrial Gases',
        'Specialty Chemicals',
        'Construction Materials',
        'Metal & Glass Containers',
        'Paper Packaging',
        'Aluminum',
        'Diversified Metals & Mining',
        'Copper',
        'Gold',
        'Precious Metals & Minerals',
        'Silver',
        'Steel',
        'Forest Products',
        'Paper Products',
        'Aerospace & Defense',
        'Building Products',
        'Construction & Engineering',
        'Electrical Components & Equipment',
        'Heavy Electrical Equipment',
        'Industrial Conglomerates',
        'Construction Machinery & Heavy Trucks',
        'Agricultural & Farm Machinery',
        'Industrial Machinery',
        'Trading Companies & Distributors',
        'Commercial Printing',
        'Environmental & Facilities Services',
        'Office Services & Supplies',
        'Diversified Support Services',
        'Security & Alarm Services',
        'Human Resource & Employment Services',
        'Research & Consulting Services',
        'Air Freight & Logistics',
        'Airlines',
        'Marine',
        'Railroads',
        'Trucking',
        'Airport Services',
        'Highways & Railtracks',
        'Marine Ports & Services',
        'Auto Parts & Equipment',
        'Tires & Rubber',
        'Automobile Manufacturers',
        'Motorcycle Manufacturers',
        'Consumer Electronics',
        'Home Furnishings',
        'Homebuilding',
        'Household Appliances',
        'Housewares & Specialties',
        'Leisure Products',
        'Apparel Accessories & Luxury Goods',
        'Footwear',
        'Textiles',
        'Casinos & Gaming',
        'Hotels Resorts & Cruise Lines',
        'Leisure Facilities',
        'Restaurants',
        'Education Services',
        'Specialized Consumer Services',
        'Distributors',
        'Internet & Direct Marketing Retail',
        'Department Stores',
        'General Merchandise Stores',
        'Apparel Retail',
        'Computer & Electronics Retail',
        'Home Improvement Retail',
        'Specialty Stores',
        'Automotive Retail',
        'Homefurnishing Retail',
        'Drug Retail',
        'Food Distributors',
        'Food Retail',
        'Hypermarkets & Super Centers',
        'Brewers',
        'Distillers & Vintners',
        'Soft Drinks',
        'Agricultural Products',
        'Packaged Foods & Meats',
        'Tobacco',
        'Household Products',
        'Personal Products',
        'Health Care Equipment',
        'Health Care Supplies',
        'Health Care Distributors',
        'Health Care Services',
        'Health Care Facilities',
        'Managed Health Care',
        'Health Care Technology',
        'Biotechnology',
        'Pharmaceuticals',
        'Life Sciences Tools & Services',
        'Diversified Banks',
        'Regional Banks',
        'Thrifts & Mortgage Finance',
        'Other Diversified Financial Services',
        'Multi-Sector Holdings',
        'Specialized Finance',
        'Consumer Finance',
        'Asset Management & Custody Banks',
        'Investment Banking & Brokerage',
        'Diversified Capital Markets',
        'Financial Exchanges & Data',
        'Mortgage REITs',
        'Insurance Brokers',
        'Life & Health Insurance',
        'Multi-line Insurance',
        'Property & Casualty Insurance',
        'Reinsurance',
        'IT Consulting & Other Services',
        'Data Processing & Outsourced Services',
        'Internet Services & Infrastructure',
        'Application Software',
        'Systems Software',
        'Communications Equipment',
        'Technology Hardware Storage & Peripherals',
        'Electronic Equipment & Instruments',
        'Electronic Components',
        'Electronic Manufacturing Services',
        'Technology Distributors',
        'Semiconductor Equipment',
        'Semiconductors',
        'Alternative Carriers',
        'Integrated Telecommunication Services',
        'Wireless Telecommunication Services',
        'Advertising',
        'Broadcasting',
        'Cable & Satellite',
        'Publishing',
        'Movies & Entertainment',
        'Interactive Home Entertainment',
        'Interactive Media & Services',
        'Electric Utilities',
        'Gas Utilities',
        'Multi-Utilities',
        'Water Utilities',
        'Independent Power Producers & Energy Traders',
        'Renewable Electricity',
        'Diversified REITs',
        'Industrial REITs',
        'Hotel & Resort REITs',
        'Office REITs',
        'Health Care REITs',
        'Residential REITs',
        'Retail REITs',
        'Specialized REITs',
        'Diversified Real Estate Activities',
        'Real Estate Operating Companies',
        'Real Estate Development',
        'Real Estate Services'
    )
);
DROP DOMAIN IF EXISTS domain_subindustry_code CASCADE;
CREATE DOMAIN domain_subindustry_code TEXT CONSTRAINT constraint_subindustry_name_predefined NOT NULL CHECK (VALUE ~ '^[0-9]{8}$');
DROP TABLE IF EXISTS subindustry CASCADE;
CREATE TABLE IF NOT EXISTS subindustry (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    code domain_subindustry_code,
    name domain_subindustry_name,
    industry_id INTEGER REFERENCES industry(id),
    sys_period TSTZRANGE NOT NULL DEFAULT TSTZRANGE(CURRENT_TIMESTAMP(0), null)
);
DROP TABLE IF EXISTS subindustry_history CASCADE;
CREATE TABLE subindustry_history (LIKE subindustry);
CREATE INDEX IF NOT EXISTS idx_subindustry_name ON subindustry(name);
CREATE INDEX IF NOT EXISTS idx_subindustry_sys_period ON subindustry(sys_period);